#include "ft_printf.h"
#include <stdio.h>

int		main()
{
	//ft_printf("%.5s\n", "Hells angels");
	//printf("%.5s\n", "Hells angels");
	//ft_printf("%c\n", 'a');
	//printf("%c\n", 'a');
	//ft_printf("%04d\n", 18);
	printf("123456789123456789\n");
	//ft_printf("%-5%|\n");
	//printf("%-5%|\n");
	//ft_printf("before %d after\n", 42);
	//printf("before %d after\n", 42);
	//ft_printf("");
	//printf("");
	//ft_printf("%X", 42);
	//printf("%X", 42);
	//ft_printf("%x\n", 42);
	//printf("%x\n", 42);
	//ft_printf("%.c\n", 0);
	//printf("%.c", 0)
	//printf("%.4d\n", 42);
	//ft_printf("%.4d\n", 42);
	//printf("%.c", 0);
	//ft_printf("%05u\n", 5);
	//printf("%05u\n", 5);
	//ft_printf("test");
	//printf("test");
	//ft_printf("%   %\n");
	//ft_printf("%-5d|\n", 12);
	//printf("%-5d|\n", 12);
	//ft_printf("1234");
	//ft_printf("%-5%");
	//printf("%-5%");
	//ft_printf("%d", 42);}
	//ft_printf("%-.12d\n", 10);
	//printf("%-.12d\n", 10);
	//ft_printf("%+4d\n", 17);
	//printf("%+4d\n", 17);
	//ft_printf("%.0%");
	//printf("%.0%");
	//check this one
	//ft_printf("%#08x", 42);
	//printf("%#08x", 42);
	//ft_printf("%#-08x", 42);
	//printf("%#-08x", 42);
	//ft_printf("%-10x\n", 42);
	//printf("%-10x", 42);
	//ft_printf("%#-6o|\n", 2500);
	//printf("%#-6o|\n", 2500);
	//ft_printf("%-10s is a string", "this");
	//printf("%-10s is a string", "this");
	//ft_printf("%-5.2s is a string", "this");
	//printf("%-5.2s is a string", "this");
	//ft_printf("%s ", "this is a string");
	//printf("%s ", "this is a string");
	//ft_printf("%    %");
	//printf("%    %");
	//ft_printf("% c", 0);
	//printf("% c", 0);
	//ft_printf("%5d\n", -42);
	//printf("%5d\n", -42);
	//ft_printf("%-+10.5d\n", 4242);
	//ft_printf("%-+10.5d\n", 4242);
	//ft_printf("%#-6o|\n", 2500);
	//printf("%#-6o|\n", 2500);
	//ft_printf("%-5.10o\n", 2500);
	//printf("%-5.10o\n", 2500);
	//ft_printf("%-5.2s is a string\n", "this");
	//printf("%-5.2s is a string\n", "this");
	//ft_printf("%-10s is a string\n", "this");
	//printf("%-10s is a string\n", "this");
	//ft_printf("%s\n", "this is a string");
	//printf("%s\n", "this is a string");
	//ft_printf("%03.2d\n", 0);
	//printf("%03.2d\n", 0);
	//ft_printf("%3.2d", -1);
	//printf("%3.2d", -1);
	//ft_printf("%03.5d\n", 1);
	//printf("%03.5d\n", 1);
	//ft_printf("%s  |\n", "this is a string");
	//printf("%s  |\n", "this is a string");
	//ft_printf("%5.2s is a string\n", "");
	//printf("%5.2s is a string\n", "");
	//ft_printf("%-5.2s is a string\n", "this");
	//printf("%-5.2s is a string\n", "this");	
	//ft_printf("%-5.2s is a string|\n", "");
	//printf("%-5.2s is a string|", "");
	//ft_printf("%s %s", NULL, string);
	//printf("%s %s", NULL, string); 
	//ft_printf("%u", 1);
	//printf("%u", 1);
	//printf("%5d %5d\n", 0, 0);
	//ft_printf("@moulitest: %.d %.0d|\n", 0, 0);
	//printf("@moulitest: %.d %.0d|", 0, 0);
	//ft_printf("%ld\n", 2147483648);
	//printf("%ld", 2147483648);
	//ft_printf("%lu", 4294967295);
	//printf("%lu", 4294967295);
	//ft_printf("@moulitest: %.d %.0d\n", 42, 43);
	//printf("@moulitest: %.d %.0d", 42, 43);
	//ft_printf("%.2s is a string\n", "");
	//printf("%.2s is a string\n", "");
	//ft_printf("%-10.5d|\n", 4242);
	//printf("%-10.5d", 4242);
	//ft_printf("%+-10.5d", 4242);
	//ft_printf("%s", "abc");
	//printf("%s", "abc");
	//ft_printf("%+d", 42);
	//printf("%+d", 42);
	//ft_printf("%5.2x", 5427);
	//printf("%5.2x", 5427);
	//ft_printf("%#8x", 42);
	//printf("%#8x", 42);
	//ft_printf("%#x", 0);
	//printf("%#x", 0);
	//ft_printf("%#-08x", 42);
	//printf("%#-08x", 42);
	//ft_printf("%5%");
	//printf("%5%");
	//ft_printf("%%");
	//printf("%%");
	//ft_printf("%s", "this is a string");
	//printf("%s", "this is a string");
	//ft_printf("%16.5o\n", 14);
	//printf("%16.5o\n", 14);
	//ft_printf("%#.1o\n", 14);
	//printf("%#.1o\n", 14);
	//ft_printf("%4.1d\n", 10);
	//printf("%4.1d\n", 10);
	//ft_printf("%#.1o\n", 14);
	//printf("%#.1o\n", 14);
	//ft_printf("%#10.1o\n", 10);
	//printf("%#10.1o\n", 10);
	//ft_printf("%#10.12o\n", 10);
	//printf("%#10.12o\n", 10);
	//ft_printf("%#10.2o\n", 10);
	//printf("%#10.2o\n", 10);
	//ft_printf("%#.6o\n", 14);
	//printf("%#.6o\n", 14);
	//ft_printf("%#1.8XX\n", 14);
	//printf("%#1.8X\n", 14);
	//printf("%#6o\n", 14);
	//printf("%04d\n", 18);
	//ft_printf(""
	//ft_printf("%hd\n", 17);
	//ft_printf("%llf\n", 1.54);
	//printf("%9000X\n", 17);
	//ft_printf("%9000d\n", 1);
	//ft_printf("%-7o\n", 12);
	//ft_printf("%-5d\n", -10);
	//ft_printf("%-1d\n", -5);
	//ft_printf( "|%-5d|%-5d|\n", 5, 12);
	//ft_printf("|%+d\n", 13);
	//printf("|%+6d\n", 13);
	//printf("%-5d\n", -10);
	//printf("%-5d\n", -5);
	//ft_printf("%5.4d\n", 5);
	//ft_printf( "|%-5d|%-5d|\n", 5, 12);
	//printf( "|%-5d|%-5d|\n", 5, 12);
	//ft_printf("%5o\n", 15);
	//printf("%5o\n", 15);
	//int a=10;
	//int* ptr =&a;
	//float f = 1.45;
	//ft_printf("-----My printf-----\n");
	//ft_printf("%u\n", 10);
	//ft_printf("%o\n", -1);
	//ft_printf("%2p\n", ptr);
	//printf("%2p\n", ptr);
	//ft_printf("%f\n", f);
	//printf("%f\n", f);
	/*
	ft_printf("both width and precision width: 4 precision: 3\n");
    ft_printf("%4.3s\n", "hellot");
    ft_printf("just width: 6 but larger than len of num\n");
    ft_printf("123\n");
	ft_printf("%6s\n", "hell");
    ft_printf("just precision: 3\n");
    ft_printf("%.3s\n", "hellot");
	*/
	/*
	ft_printf("only width\n");
	ft_printf("12345\n");
	ft_printf("%4d\n", 5);
	ft_printf("%4d\n", -5);
	ft_printf("only precision\n");
	ft_printf("%.4d\n", 5);
	ft_printf("%.4d\n", -5);
	ft_printf("precision and width\n");
	ft_printf("%4.5d\n", 5);
	ft_printf("%4.5d\n", -5);
	ft_printf("precison and width but precision larger\n");
	ft_printf("%5.4d\n", 5);
	ft_printf("%5.4d\n", -5);
	*/
	//ft_printf("-----real printf-----\n");
	//printf("% f\n", 1.450);
	//printf("%p\n",ptr);
	//printf("%f\n", f);
	//printf("%x\n", 10);
	//printf("%o\n", -1);
	/*
	printf("both width and precision width: 4 precision: 3\n");
    printf("%4.3s\n", "hellot");
    printf("just width: 6 but larger than len of num\n");
    printf("123\n");
	printf("%6s\n", "hell");
    printf("just precision: 3\n");
    printf("%.3s\n", "hellot");
	*/
	/*
	printf("only width\n");
	printf("%4d\n", 5);
	printf("%4d\n", -5);
	printf("only precision\n");
	printf("%.4d\n", 5);
	printf("%.4d\n", -5);
	printf("precision and width\n");
	printf("%4.5d\n", 5);
	printf("%4.5d\n", -5);
	printf("precison and width but precision larger\n");
	printf("%5.4d\n", 5);
	printf("%5.4d\n", -5);
	*/
	//printf("%.4d\n", 5);
	//printf("%.4d\n", -5);
	//printf("|%+6d\n", 13);
	//printf("%-7o\n", 12);

	return 0;
}
